import { MapConfig } from "@/types/map";
import { DEFAULT_THEME } from "@/lib/themes";

export const DEFAULT_MAP_CONFIG: MapConfig = {
  location: {
    lat: 40.7128,
    lng: -74.006,
    zoom: 12,
    pitch: 0,
    bearing: 0,
    label: "New York City",
  },
  basemap: "vector",
  layers: [
    { id: "land",      name: "Land",      visible: true, color: "#0d1b2a", opacity: 1 },
    { id: "landcover", name: "Landcover", visible: true, color: "#0f2035", opacity: 1 },
    { id: "water",     name: "Water",     visible: true, color: "#0a1628", opacity: 1 },
    { id: "parks",     name: "Parks",     visible: true, color: "#0e2030", opacity: 1 },
    { id: "roads",     name: "Roads",     visible: true, color: "#c9960c", opacity: 1 },
    { id: "buildings", name: "Buildings", visible: true, color: "#132035", opacity: 1 },
    { id: "rail",      name: "Rail",      visible: true, color: "#8a6b08", opacity: 1 },
    { id: "aeroway",   name: "Aeroway",   visible: true, color: "#0a1525", opacity: 1 },
  ],
  overlays: [],
  routes: [],
  cartography: {
    compass: false,
    compassStyle: "minimal",
    compassPosition: "br",
    compassSize: 64,
    compassOpacity: 0.8,
    compassMargin: 20,
    neighborhoodLabels: true,
    grid: {
      enabled: false,
      color: "#ffffff",
      opacity: 0.5,
      dashArray: [1, 0],
      showLabels: false,
      spacing: 40,
      thickness: 1,
    },
  },
  frame: {
    style: "thin",
    color: "", // Empty means follow theme
    thickness: 3,
    texture: "none",
    textureOpacity: 40,
    shadow: false,
  },
  text: {
    city: "NEW YORK",
    subtitle: "UNITED STATES",
    tagline: "40.7128° N, 74.0060° W",
    font: "Inter",
    size: 32,
    color: "",
    position: "bottom",
    alignment: "center",
    offsetX: 0,
    offsetY: 0,
  },
  poster: {
    ratio: "A3",
    width: 297,
    height: 420,
    dpi: 150,
    bgColor: "#070b12",
    layout: "single" as const,
  },
  activeThemeId: DEFAULT_THEME.id,
  themeColors: DEFAULT_THEME.colors,
  showPosterText: true,
  showOverlayLayer: false,
  overlayTopFade: 30,
  overlayBottomFade: 30,
  overlayLeftFade: 0,
  overlayRightFade: 0,
  mapRadius: 4000,
  isLocked: false,
  terrain3d: false,
  watermark: true,
  uploadedMarkers: [],
};
